# Generated by Django 6.0.2 on 2026-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ssrs_url',
            field=models.CharField(max_length=1000),
        ),
    ]
