# Generated by Django 6.0.2 on 2026-03-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_report_ssrs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPRunRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskflow_run_id', models.CharField(help_text='IICS TASKFLOW_RUN_ID that was recovered', max_length=100, unique=True)),
                ('run_start_time', models.DateTimeField(help_text='Original run start time (MST)')),
                ('original_status', models.CharField(default='SUSPENDED', help_text='Status before recovery (SUSPENDED, FAILED, etc.)', max_length=50)),
                ('recovered_at', models.DateTimeField(auto_now_add=True, help_text='When this recovery was marked in the system')),
                ('recovered_by', models.CharField(help_text='Person who recovered the run (email or name)', max_length=200)),
                ('recovery_notes', models.TextField(blank=True, help_text='Notes about what was done to recover the run')),
                ('final_status', models.CharField(default='SUCCESS', help_text='Status after recovery (SUCCESS, PARTIAL, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if recovery entry should be hidden')),
            ],
            options={
                'verbose_name': 'ERP Run Recovery',
                'verbose_name_plural': 'ERP Run Recoveries',
                'ordering': ['-recovered_at'],
            },
        ),
    ]
