# Generated by Django 6.0.2 on 2026-03-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_erprunrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='erprunrecovery',
            name='completion_time',
            field=models.DateTimeField(blank=True, help_text='When the run actually completed (after manual recovery)', null=True),
        ),
    ]
