# Generated by Django 6.0.2 on 2026-05-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_erprunrecovery_completion_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_application', models.CharField(help_text="SLA Application name (e.g., 'BI Feed - Bill Plus', 'SLV')", max_length=250)),
                ('report_date', models.DateField(help_text='Report date for the row being commented on')),
                ('comment_text', models.TextField(help_text="User's comment text")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the comment was last updated')),
                ('created_by', models.CharField(blank=True, help_text='User who created/updated the comment (optional)', max_length=200)),
            ],
            options={
                'verbose_name': 'BI Report Comment',
                'verbose_name_plural': 'BI Report Comments',
                'ordering': ['-updated_at'],
                'unique_together': {('sla_application', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='InformaticaTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='Task ID from Informatica Cloud API /tf/status/', max_length=200, unique=True)),
                ('task_name', models.CharField(help_text='Workflow or task name', max_length=500)),
                ('status', models.CharField(choices=[('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('RESTARTED', 'Restarted'), ('UNKNOWN', 'Unknown')], db_index=True, default='SUSPENDED', help_text='Current status from Informatica Cloud API', max_length=50)),
                ('is_erp_related', models.BooleanField(db_index=True, default=True, help_text='Only ERP-related tasks stored (not all workloads)')),
                ('erp_location', models.CharField(blank=True, help_text='ERP location: CDW_DSL_ERP, CDW_ASL_SAPS4, ASL_ERP_DATAHUB, etc.', max_length=200, null=True)),
                ('workflow_name', models.CharField(blank=True, db_index=True, help_text="ERP workflow name containing 'ERP', 'SAPS4', 'DATAHUB'", max_length=500, null=True)),
                ('restart_count', models.IntegerField(default=0, help_text='Number of times this task was restarted')),
                ('original_suspend_at', models.DateTimeField(blank=True, help_text='When task was originally suspended', null=True)),
                ('last_restart_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last restart attempt', null=True)),
                ('restart_completed_at', models.DateTimeField(blank=True, db_index=True, help_text='When restart was completed', null=True)),
                ('restart_completed_status', models.CharField(blank=True, help_text='Status after restart: SUCCESS, FAILED, PARTIAL, etc.', max_length=50, null=True)),
                ('restart_notes', models.TextField(blank=True, help_text='Notes about restart reason or details from API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When record was first captured')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time from API')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Auto-delete record after this date (2 days from creation)')),
            ],
            options={
                'verbose_name': 'Informatica Task Status',
                'verbose_name_plural': 'Informatica Task Statuses',
                'db_table': 'informatica_task_status',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_erp_related', 'status'], name='informatica_is_erp__cdf3e3_idx'), models.Index(fields=['expires_at'], name='informatica_expires_9a3395_idx'), models.Index(fields=['task_id'], name='informatica_task_id_554c35_idx'), models.Index(fields=['workflow_name'], name='informatica_workflo_b897e2_idx'), models.Index(fields=['restart_completed_at'], name='informatica_restart_339ddf_idx')],
            },
        ),
    ]
