# Level3 BI Email Scheduler - Setup Script
# This script creates a Windows Scheduled Task to send Level3 BI reports every 3 hours
#
# Usage: Run this script as Administrator
#        .\setup_email_scheduler.ps1

param(
    [Parameter(Mandatory=$false)]
    [string]$TaskName = "Level3_BI_Email_Report",
    
    [Parameter(Mandatory=$false)]
    [string]$ProjectPath = "C:\Users\ab64033\source\repos\infa_monitor_portal\monitorportal",
    
    [Parameter(Mandatory=$false)]
    [string]$VenvPath = "C:\Users\ab64033\source\repos\infa_monitor_portal\monitorportal\.venv",
    
    [Parameter(Mandatory=$false)]
    [switch]$EnableScreenshots,
    
    [Parameter(Mandatory=$false)]
    [string]$CustomRecipients = ""
)

Write-Host @"
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║       Level3 BI Email Report - Scheduler Setup              ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"@ -ForegroundColor Cyan

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "`n⚠️  WARNING: This script should be run as Administrator for best results." -ForegroundColor Yellow
    Write-Host "   The scheduled task may not run with the correct permissions." -ForegroundColor Yellow
    
    $continue = Read-Host "`nDo you want to continue anyway? (yes/no)"
    if ($continue -ne "yes") {
        Write-Host "`nExiting. Please run as Administrator." -ForegroundColor Red
        exit 1
    }
}

Write-Host "`n📋 Configuration:" -ForegroundColor Green
Write-Host "  Task Name:      $TaskName"
Write-Host "  Project Path:   $ProjectPath"
Write-Host "  Virtual Env:    $VenvPath"
Write-Host "  Screenshots:    $(if ($EnableScreenshots) { 'Enabled' } else { 'Disabled' })"
if ($CustomRecipients) {
    Write-Host "  Recipients:     $CustomRecipients"
} else {
    Write-Host "  Recipients:     Default (Naresh.m@lumen.com, Prithviraj.Nayak@lumen.com)"
}

# Verify paths exist
if (-not (Test-Path $ProjectPath)) {
    Write-Host "`n❌ ERROR: Project path not found: $ProjectPath" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $VenvPath)) {
    Write-Host "`n❌ ERROR: Virtual environment not found: $VenvPath" -ForegroundColor Red
    Write-Host "   Please create virtual environment first." -ForegroundColor Yellow
    exit 1
}

# Create the PowerShell script that will be executed by the scheduled task
$executorScriptPath = Join-Path $ProjectPath "run_email_report.ps1"

Write-Host "`n📝 Creating executor script: $executorScriptPath" -ForegroundColor Cyan

$executorScript = @"
# Level3 BI Email Report Executor
# This script is run by Windows Task Scheduler every 3 hours
# Auto-generated by setup_email_scheduler.ps1

`$ErrorActionPreference = "Stop"

# Activate virtual environment
& "$VenvPath\Scripts\Activate.ps1"

# Change to project directory
Set-Location "$ProjectPath"

# Build command
`$command = "python manage.py send_level3_bi_email"

"@

if ($EnableScreenshots) {
    $executorScript += "`$command += ' --screenshot'`n"
}

if ($CustomRecipients) {
    $executorScript += "`$command += ' --recipients ""$CustomRecipients""'`n"
}

$executorScript += @"

# Log output to file
`$logDir = Join-Path "$ProjectPath" "logs"
if (-not (Test-Path `$logDir)) {
    New-Item -ItemType Directory -Path `$logDir -Force | Out-Null
}

`$logFile = Join-Path `$logDir "email_report_`$(Get-Date -Format 'yyyyMMdd').log"
`$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

# Execute command and log
try {
    Write-Output "`n[`$timestamp] Starting Level3 BI email report..." | Tee-Object -FilePath `$logFile -Append
    Invoke-Expression `$command 2>&1 | Tee-Object -FilePath `$logFile -Append
    Write-Output "[`$timestamp] Email report completed successfully.`n" | Tee-Object -FilePath `$logFile -Append
    exit 0
} catch {
    Write-Output "[`$timestamp] ERROR: `$_`n" | Tee-Object -FilePath `$logFile -Append
    exit 1
}
"@

# Write executor script
$executorScript | Out-File -FilePath $executorScriptPath -Encoding UTF8 -Force

Write-Host "✓ Executor script created successfully" -ForegroundColor Green

# Create scheduled task
Write-Host "`n📅 Creating scheduled task..." -ForegroundColor Cyan

# Remove existing task if it exists
$existingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existingTask) {
    Write-Host "  Removing existing task..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

# Create scheduled task action
$action = New-ScheduledTaskAction `
    -Execute "PowerShell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$executorScriptPath`"" `
    -WorkingDirectory $ProjectPath

# Create triggers for every 3 hours (8 times per day)
$triggers = @()
for ($hour = 0; $hour -lt 24; $hour += 3) {
    $time = "{0:D2}:00" -f $hour
    $trigger = New-ScheduledTaskTrigger -Daily -At $time
    $triggers += $trigger
}

# Create task settings
$settings = New-ScheduledTaskSettings `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable `
    -MultipleInstances IgnoreNew

# Get current user
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest

# Register the task
try {
    # Create task with first trigger
    Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $action `
        -Trigger $triggers[0] `
        -Settings $settings `
        -Principal $principal `
        -Description "Sends Level3 BI monitoring report via email every 3 hours. Auto-generated by Monitor Portal." `
        -Force | Out-Null
    
    # Add additional triggers
    $task = Get-ScheduledTask -TaskName $TaskName
    for ($i = 1; $i -lt $triggers.Count; $i++) {
        $task.Triggers += $triggers[$i]
    }
    $task | Set-ScheduledTask | Out-Null
    
    Write-Host "✓ Scheduled task created successfully" -ForegroundColor Green
    
} catch {
    Write-Host "`n❌ ERROR: Failed to create scheduled task: $_" -ForegroundColor Red
    exit 1
}

# Display task information
Write-Host "`n📊 Scheduled Task Details:" -ForegroundColor Green
$task = Get-ScheduledTask -TaskName $TaskName
Write-Host "  Task Name:    $($task.TaskName)"
Write-Host "  State:        $($task.State)"
Write-Host "  Author:       $($task.Author)"

Write-Host "`n  Execution Times (every 3 hours):" -ForegroundColor Cyan
foreach ($trigger in $task.Triggers) {
    if ($trigger.StartBoundary) {
        $time = ([DateTime]::Parse($trigger.StartBoundary)).ToString('HH:mm')
        Write-Host "    - $time"
    }
}

Write-Host "`n  Log Files Location:" -ForegroundColor Cyan
Write-Host "    $ProjectPath\logs\email_report_YYYYMMDD.log"

# Test email configuration (optional)
Write-Host "`n" -NoNewline
$testEmail = Read-Host "Do you want to send a test email now? (yes/no)"

if ($testEmail -eq "yes") {
    Write-Host "`n📧 Sending test email..." -ForegroundColor Cyan
    
    Set-Location $ProjectPath
    & "$VenvPath\Scripts\Activate.ps1"
    
    if ($CustomRecipients) {
        python manage.py send_level3_bi_email --test --recipients $CustomRecipients
    } else {
        python manage.py send_level3_bi_email --test
    }
}

Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║              ✓ Setup Completed Successfully!                ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

📋 Next Steps:
   1. Verify email configuration in monitorportal/monitorportal/settings.py
   2. Check scheduled task in Task Scheduler: taskschd.msc
   3. Monitor logs in: $ProjectPath\logs\

⚙️  Useful Commands:
   
   # Send email manually
   python manage.py send_level3_bi_email
   
   # Send with screenshot
   python manage.py send_level3_bi_email --screenshot
   
   # Send test email
   python manage.py send_level3_bi_email --test
   
   # View scheduled task
   Get-ScheduledTask -TaskName "$TaskName"
   
   # Run task immediately
   Start-ScheduledTask -TaskName "$TaskName"
   
   # Disable task
   Disable-ScheduledTask -TaskName "$TaskName"
   
   # Remove task
   Unregister-ScheduledTask -TaskName "$TaskName"

"@ -ForegroundColor Green

Write-Host "Setup complete! The email report will run automatically every 3 hours." -ForegroundColor Cyan
Write-Host "Check Task Scheduler (taskschd.msc) to verify the task.`n" -ForegroundColor Yellow
