"""
Django settings for monitorportal project.

Generated by 'django-admin startproject'.

This settings.py is customized for:
- Monitoring Portal (Django app: portal)
- SSRS dashboard portal pages + static UI
- Development run on localhost
- Future readiness for Oracle and AI integration
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# SECURITY (Development)
# -----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
# For production: set SECRET_KEY via environment variable.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
# ✅ PRODUCTION-READY: Reads from environment variable, defaults to False
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

# ✅ PRODUCTION-READY: Allowed hosts from environment variable
# Set DJANGO_ALLOWED_HOSTS="host1,host2,host3" in production
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if not DEBUG else ["*"]

# -----------------------------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your portal app
    "portal",
]

# -----------------------------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ✅ PRODUCTION: Serve static files efficiently
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "portal.middleware.DevRemoteUserMiddleware",  # DEV ONLY: Simulates SSO for local testing
    "django.contrib.auth.middleware.RemoteUserMiddleware",  # SSO CUID capture
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------------------------------------------------
# URL / TEMPLATES / WSGI
# -----------------------------------------------------------------------------
ROOT_URLCONF = "monitorportal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                # ✅ Add this:
                "portal.context_processors.nav_apps",
            ],
        },
    },
]

WSGI_APPLICATION = "monitorportal.wsgi.application"

# -----------------------------------------------------------------------------
# CACHING (Performance Optimization)
# -----------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'infa-monitor-cache',
        'TIMEOUT': 120,  # Default cache timeout in seconds (2 minutes)
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of cache entries
        }
    }
}

# Cache middleware (optional - for whole page caching)
# MIDDLEWARE = [
#     'django.middleware.cache.UpdateCacheMiddleware',  # Must be first
#     ...existing middleware...
#     'django.middleware.cache.FetchFromCacheMiddleware',  # Must be last
# ]

# -----------------------------------------------------------------------------
# DATABASE (SQLite for dev)
# -----------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -----------------------------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# AUTHENTICATION BACKENDS (SSO Support)
# -----------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',  # SSO via REMOTE_USER header
    'django.contrib.auth.backends.ModelBackend',  # Fallback to database users
]

# -----------------------------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"

# Set to India timezone for your monitoring portal
TIME_ZONE = "Asia/Kolkata"

USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# STATIC FILES (CSS/JS/Images)
# -----------------------------------------------------------------------------
STATIC_URL = "/static/"

# ✅ PRODUCTION: Collect static files to this directory
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# ✅ PRODUCTION: WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Additional static file directories (if needed)
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# -----------------------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------------------
# FUTURE (Oracle configuration placeholder)
# -----------------------------------------------------------------------------
# When you connect Oracle later, we will change DATABASES like below:
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.oracle",
#         "NAME": os.getenv("ORACLE_DSN", "host:1521/servicename"),
#         "USER": os.getenv("ORACLE_USER", ""),
#         "PASSWORD": os.getenv("ORACLE_PASSWORD", ""),
#     }
# }
#
# Note: For Oracle, we typically use python-oracledb driver + proper client mode
# depending on your org requirements.

X_FRAME_OPTIONS = "SAMEORIGIN"

# -----------------------------------------------------------------------------
# EMAIL CONFIGURATION (for automated reports and alerts)
# -----------------------------------------------------------------------------
# Email backend options:
# - smtp: Send via SMTP (requires firewall access)
# - file: Save emails as .eml files (works without admin access)
# - console: Print to console (development only)
EMAIL_BACKEND_TYPE = os.getenv('EMAIL_BACKEND_TYPE', 'file')  # smtp, file, or console

if EMAIL_BACKEND_TYPE == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
elif EMAIL_BACKEND_TYPE == 'file':
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')  # Folder to save emails
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP Configuration for Lumen/Corporate Email (when using SMTP backend)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mailrelay.corp.intranet')  # Lumen internal SMTP relay
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))  # Standard SMTP port
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # No auth required for relay
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'naresh.m@lumen.com')

# URL for screenshot capture (used by email service)
SERVER_URL = os.getenv('SERVER_URL', 'http://127.0.0.1:8000')

# -----------------------------------------------------------------------------
# INFORMATICA POWERCENTER CONFIGURATION (for workflow restart)
# -----------------------------------------------------------------------------
# Path to pmcmd (PowerCenter Command Line Program)
# Windows example: 'C:\\Program Files\\Informatica\\PowerCenter\\server\\bin\\pmcmd.exe'
# Linux example: '/opt/informatica/server/bin/pmcmd'
# Local Windows installation - updated to actual install location
INFORMATICA_PMCMD_PATH = os.getenv('INFORMATICA_PMCMD_PATH', r'C:\Informatica\CDIPC_Client\clients\PowerCenterClient\CommandLineUtilities\PC\server\bin\PmCmd.exe')
# Production Linux server path (default for deployment)
#INFORMATICA_PMCMD_PATH = os.getenv('INFORMATICA_PMCMD_PATH', '/prd1/usr/local/informatica/CDIPC/Informatica/platform/home/server/bin/pmcmd')

# Server and connection details
INFORMATICA_HOST = os.getenv('INFORMATICA_HOST', 'azeus2lipcp01')
INFORMATICA_PORT = os.getenv('INFORMATICA_PORT', '6005')

# Repository and domain configuration
INFORMATICA_DOMAIN = os.getenv('INFORMATICA_DOMAIN', 'Domain_INFA_PRD1')
INFORMATICA_REPOSITORY = os.getenv('INFORMATICA_REPOSITORY', 'PCREPO_PRD1_01')
INFORMATICA_INTEGRATION_SERVICE = os.getenv('INFORMATICA_INTEGRATION_SERVICE', 'IS_GRID_BI')

# Credentials for pmcmd authentication
# ✅ PRODUCTION-READY: No hardcoded passwords in production
INFORMATICA_USERNAME = os.getenv('INFORMATICA_USERNAME', 'ab64033')  # Dev default only
INFORMATICA_PASSWORD = os.getenv('INFORMATICA_PASSWORD')  # ⚠️ MUST be set via environment variable in production!

# User Security Domain (required for CTL/Lumen users)
INFORMATICA_USER_SECURITY_DOMAIN = os.getenv('INFORMATICA_USER_SECURITY_DOMAIN', 'CTL')

# Default folder for workflows (can be overridden per restart request)
INFORMATICA_DEFAULT_FOLDER = os.getenv('INFORMATICA_DEFAULT_FOLDER', 'Default')

# -----------------------------------------------------------------------------
# DATABRICKS ODBC CONFIGURATION (for ADF monitoring data)
# -----------------------------------------------------------------------------
# User DSN name configured in Windows ODBC Data Sources
DATABRICKS_DSN = os.getenv('DATABRICKS_DSN', 'Databricks_Conn')

# Table containing ADF/Databricks metadata
DATABRICKS_ADF_TABLE = os.getenv('DATABRICKS_ADF_TABLE', 'asl.metadata_framework.ingestion_log')
