"""
Django settings for monitorportal project.

Generated by 'django-admin startproject'.

This settings.py is customized for:
- Monitoring Portal (Django app: portal)
- SSRS dashboard portal pages + static UI
- Development run on localhost
- Future readiness for Oracle and AI integration
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# SECURITY (Development)
# -----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
# For production: set SECRET_KEY via environment variable.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Local dev hosts + internal network sharing
ALLOWED_HOSTS = [
    "127.0.0.1", 
    "localhost",
    "10.161.206.34",  # Your corporate IP - for internal Lumen network sharing
    "192.168.0.100",  # Your local IP
    "*",  # Allow all (temporary - for demo/testing only)
]

# -----------------------------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your portal app
    "portal",
]

# -----------------------------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "portal.middleware.DevRemoteUserMiddleware",  # DEV ONLY: Simulates SSO for local testing
    "django.contrib.auth.middleware.RemoteUserMiddleware",  # SSO CUID capture
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------------------------------------------------
# URL / TEMPLATES / WSGI
# -----------------------------------------------------------------------------
ROOT_URLCONF = "monitorportal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                # ✅ Add this:
                "portal.context_processors.nav_apps",
            ],
        },
    },
]

WSGI_APPLICATION = "monitorportal.wsgi.application"

# -----------------------------------------------------------------------------
# CACHING (Performance Optimization)
# -----------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'infa-monitor-cache',
        'TIMEOUT': 120,  # Default cache timeout in seconds (2 minutes)
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of cache entries
        }
    }
}

# Cache middleware (optional - for whole page caching)
# MIDDLEWARE = [
#     'django.middleware.cache.UpdateCacheMiddleware',  # Must be first
#     ...existing middleware...
#     'django.middleware.cache.FetchFromCacheMiddleware',  # Must be last
# ]

# -----------------------------------------------------------------------------
# DATABASE (SQLite for dev)
# -----------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -----------------------------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# AUTHENTICATION BACKENDS (SSO Support)
# -----------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',  # SSO via REMOTE_USER header
    'django.contrib.auth.backends.ModelBackend',  # Fallback to database users
]

# -----------------------------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"

# Set to India timezone for your monitoring portal
TIME_ZONE = "Asia/Kolkata"

USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# STATIC FILES (CSS/JS/Images)
# -----------------------------------------------------------------------------
STATIC_URL = "static/"

# For dev, this is optional, but good practice if you keep static outside apps:
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# -----------------------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------------------
# FUTURE (Oracle configuration placeholder)
# -----------------------------------------------------------------------------
# When you connect Oracle later, we will change DATABASES like below:
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.oracle",
#         "NAME": os.getenv("ORACLE_DSN", "host:1521/servicename"),
#         "USER": os.getenv("ORACLE_USER", ""),
#         "PASSWORD": os.getenv("ORACLE_PASSWORD", ""),
#     }
# }
#
# Note: For Oracle, we typically use python-oracledb driver + proper client mode
# depending on your org requirements.

X_FRAME_OPTIONS = "SAMEORIGIN"

# -----------------------------------------------------------------------------
# INFORMATICA POWERCENTER CONFIGURATION (for workflow restart)
# -----------------------------------------------------------------------------
# Path to pmcmd (PowerCenter Command Line Program)
# Windows example: 'C:\\Program Files\\Informatica\\PowerCenter\\server\\bin\\pmcmd.exe'
# Linux example: '/opt/informatica/server/bin/pmcmd'
INFORMATICA_PMCMD_PATH = os.getenv('INFORMATICA_PMCMD_PATH', '/prd1/app/informatica/infa_shared/server/bin/pmcmd')

# Server and connection details
INFORMATICA_HOST = os.getenv('INFORMATICA_HOST', 'azeus2lipcp01')
INFORMATICA_PORT = os.getenv('INFORMATICA_PORT', '6005')

# Repository and domain configuration
INFORMATICA_DOMAIN = os.getenv('INFORMATICA_DOMAIN', 'Domain_INFA_PRD1')
INFORMATICA_REPOSITORY = os.getenv('INFORMATICA_REPOSITORY', 'PCREPO_PRD1_01')
INFORMATICA_INTEGRATION_SERVICE = os.getenv('INFORMATICA_INTEGRATION_SERVICE', 'infr01p_app')

# Credentials for pmcmd authentication
INFORMATICA_USERNAME = os.getenv('INFORMATICA_USERNAME', 'Ab64033')
INFORMATICA_PASSWORD = os.getenv('INFORMATICA_PASSWORD', 'Samsungs26@123')

# Default folder for workflows (can be overridden per restart request)
INFORMATICA_DEFAULT_FOLDER = os.getenv('INFORMATICA_DEFAULT_FOLDER', 'Default')
