"""
Django settings for monitorportal project.

Generated by 'django-admin startproject'.

This settings.py is customized for:
- Monitoring Portal (Django app: portal)
- SSRS dashboard portal pages + static UI
- Development run on localhost
- Future readiness for Oracle and AI integration
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# SECURITY (Development)
# -----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
# For production: set SECRET_KEY via environment variable.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Local dev hosts
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# -----------------------------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your portal app
    "portal",
]

# -----------------------------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------------------------------------------------
# URL / TEMPLATES / WSGI
# -----------------------------------------------------------------------------
ROOT_URLCONF = "monitorportal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                # ✅ Add this:
                "portal.context_processors.nav_apps",
            ],
        },
    },
]

WSGI_APPLICATION = "monitorportal.wsgi.application"

# -----------------------------------------------------------------------------
# DATABASE (SQLite for dev)
# -----------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -----------------------------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"

# Set to India timezone for your monitoring portal
TIME_ZONE = "Asia/Kolkata"

USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# STATIC FILES (CSS/JS/Images)
# -----------------------------------------------------------------------------
STATIC_URL = "static/"

# For dev, this is optional, but good practice if you keep static outside apps:
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# -----------------------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------------------
# FUTURE (Oracle configuration placeholder)
# -----------------------------------------------------------------------------
# When you connect Oracle later, we will change DATABASES like below:
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.oracle",
#         "NAME": os.getenv("ORACLE_DSN", "host:1521/servicename"),
#         "USER": os.getenv("ORACLE_USER", ""),
#         "PASSWORD": os.getenv("ORACLE_PASSWORD", ""),
#     }
# }
#
# Note: For Oracle, we typically use python-oracledb driver + proper client mode
# depending on your org requirements.

X_FRAME_OPTIONS = "SAMEORIGIN"